### ISSUE TITLE
Regarding the latest version of Minecraft plug-in, is there any update?

### ISSUE THREAD

**Issue by Shiroko253** [gecolay/GMusic#7]
Hello, I am a Minecraft server player. The server I play on uses your plug-in. I have a question for you. Do you plan to upgrade your plug-in to a version such as 1.21/1.22?

**Comment by Diamondback88** [comment]
I'm currently working on a fork of the plugin that will at least fix the basic GUI functions for 1.21. Keep watching this issue

**Comment by Diamondback88** [comment]
Update: If you build my fork from source [here](https://github.com/Diamondback88/GMusic), you should be able to use all of the GUI stuff again working totally fine!
